name: Build and deploy action
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: debug1
        run: ls -la
      - name: clone code
        uses: actions/checkout@v2
      -name: debug2
       run: ls -la
